name: aichat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  record: ^5.0.4
  permission_handler: ^11.2.0
  path_provider: ^2.1.2
  audioplayers: ^6.1.0
  file_picker: ^8.1.4
  image_picker: ^1.0.7
  chewie: ^1.7.5
  just_audio: ^0.9.36
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_quill: ^10.8.5
  #flutter_autosize_screen: ^1.0.1
  flutter_screenutil: ^5.9.3
  camera: ^0.11.0+2
  #video_thumbnail: ^0.5.3
  id3: ^1.0.2
  flutter_local_notifications: ^18.0.1
  #android_alarm_manager_plus: ^3.0.4
  #background_fetch: ^1.3.7
  timezone: ^0.10.0
  audio_session: ^0.1.23
  dio: ^5.7.0
  share_plus: ^10.1.3
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.2.1
  responsive_framework: ^1.5.1
  livekit_client: ^2.4.0
  livekit_components: ^1.1.1
  http: ^1.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:  
    - assets/background.mp4
    - assets/logo.png
    - assets/background.jpg
    - assets/rabbit.png
    - assets/AIStudy.png
    - assets/show.png
    - assets/tv.png
    - assets/homework.png
    - assets/video.png
    - assets/reading.png
    - assets/parent.png
    - assets/readinghistory.png
    - assets/listening.png
    - assets/star.png    
    - assets/flower.png  
    - assets/medal.png
    - assets/container.png
    - assets/StudyRoom.png
    - assets/message.png
    - assets/school.png
    - assets/setting.png
    - assets/teacher.png
    - assets/question_bank.png 
    - assets/textbook_manage.png
    - assets/points_manage.png
    - assets/show_manage.png
    - assets/homework_assign.png 
    - assets/class_manage.png
    - assets/cloud.png 
    - assets/teacher_container.png
    - assets/class2.png
    - assets/staff_manage.png
    - assets/student_manage.png
    - assets/universe.png
    - assets/back_button.png
    - assets/like.png
    - assets/addbackground.png
    - assets/workbackground.png
    - assets/addbutton.png
    - assets/playsound.png
    - assets/newreturn.png
    - assets/freestudy.png
    - assets/fixstudy.png
    - assets/fsbg.png
    - assets/happylisten.png
    - assets/rhythm.png
    - assets/writing.png
    - assets/writing1.png
    - assets/listening_comp.png
    - assets/listening1.png
    - assets/reading_level.png
    - assets/speaking.png
    - assets/cartoon.png
    - assets/points.png
    - assets/back_button.png
    - assets/superstar.png
    - assets/schoolstar.png
    - assets/classstar.png
    - assets/mystar.png
    - assets/rewardbg.png
    - assets/no_rewards.png
    - assets/reward_main.png
    - assets/questionmark.png
    - assets/pointrulebg.png
    - assets/recordtitle.png
    - assets/backbutton1.png
    - assets/rewardbg.png
    - assets/rewardedprize.png
    - assets/studentpointslogo.png
    - assets/recordedgift.png
    - assets/prize1.png
    - assets/prize2.png
    - assets/happylistenbg.png
    - assets/happylistenbg1.png
    - assets/test_audio.mp3
    - assets/test_audio2.mp3
    - assets/test_audio3.mp3
    - assets/test_video.mp4
    - assets/rhythmbg.png
    - assets/sunset.png
    - assets/childmusic.png
    - assets/levelcheck.png
    - assets/passmedal.png
    - assets/historyrecord.png
    - assets/zuopinxiuchangbg1.png
    - assets/starworks.png
    - assets/schoolworks.png
    - assets/classworks.png
    - assets/myworks.png
    - assets/nullyellow.png
    - assets/nullsilver.png
    - assets/cartoonvideologo.png
    - assets/gradedreadinglogo.png
    - assets/happylistenlogo.png
    - assets/eye_icon.png
    - assets/setting_icon.png
    - assets/report_icon.png
    - assets/settingbg.png
    - assets/parentbg.png
    - assets/personalbg.png
    - assets/AIStudyRoom.png
    - assets/homeworkbg.png
    - assets/assignmentbutton.png
    - assets/editbutton.png
    - assets/default_cover.png
    - assets/popuphomework.png
    - assets/parentguide.png
    - assets/notification.png
    - assets/video1.mp4
    - assets/video2.mp4
    - assets/checklist_icon.png
    - assets/audio_icon.png
    - assets/video_icon.png
    - assets/image_icon.png
    - assets/applogin.png
    - assets/loginbg.png
    - assets/rewardbg1.png
    - assets/taskicon.png
    - assets/test_mainbg.png
    - assets/p1.png
    - assets/cartoon_videobg1.png
    - assets/happylistenicon.png
    - assets/points_shop.png
    - assets/huiben.jpg
    - assets/settings.jpg
    - assets/theme.png
    - assets/statistics.png
    - assets/feedback.png
    - assets/quit.png










    
